[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  base = "Live_Projects/fullStack/cpauto-code/live-code"

[context.staging]
  base = "Live_Projects/fullStack/cpauto-code/live-code"


