[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  base = "Live_Projects/fullStack/cpauto-code/live-code"

[context.staging]
  base = "Live_Projects/fullStack/cpauto-code/live-code"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept, Range"


