name: Netlify Deploy Pipeline (Parcel + Webflow)

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Get commit hash
        id: vars
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build with Parcel
        run: npm run build
        env:
          BUILD_VERSION: ${{ steps.vars.outputs.hash }}

      # Staging (branch)
      - name: Deploy to Netlify (staging)
        if: github.ref == 'refs/heads/staging'
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './dist'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          deploy-message: "Staging build ${{ steps.vars.outputs.hash }}"
          alias: 'staging'

      # Production (branch)
      - name: Deploy to Netlify (production)
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './dist'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID_PROD }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          deploy-message: "Production build ${{ steps.vars.outputs.hash }}"

      # PR Preview
      - name: Deploy Preview for PR
        if: github.event_name == 'pull_request'
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './dist'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          deploy-message: "Preview for PR #${{ github.event.number }}"
          alias: "pr-${{ github.event.number }}"
