# Example config for the Academic Paper Engine (prototype)
# Select 1–3 papers per cycle from arXiv within a recent time window.

topics:
  - computational linguistics
  - neuroscience

# Papers per cycle (1–3 recommended)
n: 2

# Look-back window (days)
days: 21

# Output file (omit to print to console)
outfile: digest.md

# Reading level guidance for the “How to read” note
# one of: beginner | intermediate | expert
level: intermediate
